plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.20'
    id 'maven-publish'
}
version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }
repositories { mavenCentral() }
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}
java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}
tasks.withType(JavaCompile).configureEach { options.release = 25 }
jar { from('LICENSE') { rename { "${it}_${project.base.archivesName.get()}" } } }
publishing { publications { mavenJava(MavenPublication) { from components.java } } }

fabricApi {
    configureTests {
        createSourceSet = true
        modId = 'voodoo-test'
        enableGameTests = true
        enableClientGameTests = true
        eula = true
    }
}
